### PR TITLE
Replaces phantomcss with a fresh Drupal specific BackstopJS fork

### PR DESCRIPTION
**Pull request by axe312ger**
Just do the "normal" BackstopJS workflow. Use the following command to get an example backstop.json in your root dir of the frontend toolkit:

``` bash
cd ./node_modules/backstopjs
gulp genConfig
```

To create fresh references:

``` bash
cd ./node_modules/backstopjs
gulp references
```

To run the tests:

``` bash
cd ./node_modules/backstopjs
gulp test
```

### CODE REVIEW

**Comment by axe312ger** [comment]
screen shot 2015-08-03 at 12 44 06

Example config json:

``` json
{
  "issueId":2474091,
  "baseUrl":"http://d8.dev",
  "viewports": [
    {
      "name": "phone",
      "width": 320,
      "height": 480
    },
    {
      "name": "tablet_v",
      "width": 568,
      "height": 1024
    },
    {
      "name": "tablet_h",
      "width": 1024,
      "height": 768
    }
  ],
  "scenarios": [
    {
      "label": "Node full",
      "url": "node/1",
      "loginRequired":0,
      "hideSelectors": [],
      "removeSelectors": [
      ],
      "selectors": [
        ".node--view-mode-full > .node__content"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.05
    },
    {
      "label": "Node edit form",
      "url": "node/1/edit",
      "loginRequired":1,
      "hideSelectors": [],
      "removeSelectors": [
        "#toolbar-administration"
      ],
      "selectors": [
        "form.node-form",
        ".field-type-image",
        ".field-name-field-file"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.05
    }
  ]
}
```

**Comment by axe312ger** [comment]
Also I want to note that there is still room for improvement. The original backstopjs is powerful but dirty, that might take some time.

**Comment by lewisnyman** [comment]
Sorry I missed this before. So this automatically logs in as admin? What does the issue ID do? What else is different to the original backstop?

**Comment by axe312ger** [comment]
- Slimerjs integration (Should be already pushed to the original repo)
- Yes, it logs in as admin:admin (That feature might also be integrated to backstopjs, but he needs time)
- The issueid is basically for identification. It is not required at all.
- Some more small fixes which hopefully will be commited to backstopjs also.

I am in contact with the original maintainer. Since he fixed the whitespace issues a few days ago, pull requests and direct contribution is way easier :) -> https://github.com/garris/BackstopJS/commit/bb0850b2c3461ee7f90c5f5f19b56cf905813577

**Pull request closed without merging**
